### ISSUE TITLE
getting below issue while build on CI 

### ISSUE THREAD

**Issue by shaileshme118** [nigelpoulton/pluralsight-docker-CI#8]
mocha
module.js:328
    throw err;
    ^

Error: Cannot find module 'supertest'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/pluralsight-docker-CI/test/test.js:4:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /opt/circleci/nodejs/v4.2.6/lib/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/opt/circleci/nodejs/v4.2.6/lib/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/opt/circleci/nodejs/v4.2.6/lib/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/opt/circleci/nodejs/v4.2.6/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

mocha returned exit code 1

**Comment by robby-prescott-concord** [comment]
I am getting this same issue
